### ISSUE TITLE
foreground color colors image

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/libRocket#7]
I noticed this bug some years ago, if I type `^1[granger]` in game, in some place (typically libRocket ui elements), the granger icon is colored in red. I've never reported it until now because at first I was not sure if it was a bug or a feature, then time has passed, and for all this time I was not thinking the issue would be that problematic. So I just forgot the issue.

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200112-214544-001.unvanquished-librocket-colored-images.jpg)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200112-214544-001.unvanquished-librocket-colored-images.jpg)

While reporting Unvanquished/Unvanquished#1151 “_Something unknown is making our game darker than it should_” I had the idea that since one of the major difference between the [Xonotic Dæmon Glue](https://gitlab.com/xonotic/daemon-glue) and the Unvanquished game code is the Unvanquished UI uses libRocket, maybe that bug was related to libRocket, either in libRocket, either in our RML/RCSS code.

I looked at our UI system with hope to find bugs. At the same time I was investigating Unvanquished/Unvanquished#1152 “_Grey on grey map loading screen when missing levelshot_”. I first looked at our RML/RCSS code believing it would a bug in our RML/RCSS code and I found a bug… in libRocket, and this is the bug causing the red granger bug.

There is no proof this libRocket bug is the one causing Unvanquished/Unvanquished#1151, but at least, it's a real bug.

## The bug

If you type this or this in a browser:

```html
<img style="color: black;" src="image.png" />
<body style="color: black;"><img src="image.png" />text</body>
```

The image will be displayed unmodified. The `color` property would only affect text, not the image.

But in libRocket, it will color the image, which is wrong.

## Some examples

First example, this is how currently looks our map loading screen (chasm map), it has a grey color set as foreground color on `body` element:

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234353.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234353.unvanquished-librocket-colored-images.png)

This is how looks the map loading screen with a white foreground color set on `img` element:

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234323.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234323.unvanquished-librocket-colored-images.png)

With a white foreground color set on `body` element:

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200123-001001.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200123-001001.unvanquished-librocket-colored-images.png)

With a yellow foreground color set on `img` element:

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234034.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234034.unvanquished-librocket-colored-images.png)

With a yellow foreground color set on `body` element:

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200123-001220.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200123-001220.unvanquished-librocket-colored-images.png)

With a black foreground color set on `img` element and grey foreground color set on `body` element.

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234435.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200122-234435.unvanquished-librocket-colored-images.png)

See how the image is completely dark in the late case.

What we discover is that not only it is wrong to color the image with foreground, but that coloring process is not additive. I don't know how to name that but the color of the image is substracted the same way you have to substract the white color to get the foreground color. If you have a foreground that is 30% darker than white, your image will be 30% darker than its original color.

---

Second example with vega map, how map loading screen is currently displayed:

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200126-013446.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200126-013446.unvanquished-librocket-colored-images.png)

How it looks when foreground color is set to white on `body` element:

[![librocket colored images](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200123-000018.unvanquished-librocket-colored-images.png)](https://dl.illwieckz.net/b/librocket/bugs/colored-images/20200123-000018.unvanquished-librocket-colored-images.png)

We may still want to color the text element, but I've set the `color` property on `body` element to showcase the bug: the foreground color set on a parent element will modify the child image.

There is two ways to workaround the bug:  

1. never use inheritance on foreground color and set the foreground color on every element that requires a customized one. This is the hardest choice but avoids any collateral bugs.
2. style the `img` element to white. This has a collateral bug of making a missing image looking like a white rectangle, using the foreground color while we would expect the background color.

**Comment by illwieckz** [comment]
People on RmlUi's gitter said this issue was fixed, that's a call for an update.

**Comment by Gireen** [comment]
I think we use font color for icons in the hud and probably also beacons. Which would also work with an image-color property. 
But for emoticons the current behavior could be useful for a new feature. When we add white emoticons they can be colored like normal text. We would just need to distinguish between colored and white images and give the latter as default white font color.

**Comment by illwieckz** [comment]
Yep, RmlUi has special `image-color` property to reproduce the same behavior this faulty `color` property has. We must be sure not rely on bugs as features.

**Comment by illwieckz** [comment]
I assume `0.53.0/sync` branch with RmlUi fixes that.

**Comment by necessarily-equal** [comment]
The two screenshots of the vega loading screen make me think of https://github.com/Unvanquished/Unvanquished/issues/1834 though :eyes:

**Comment by necessarily-equal** [comment]
Heh, ninja'ed

**Comment by illwieckz** [comment]
🥷️
