### ISSUE TITLE
rebase on RmlUi (maintained libRocket fork)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/libRocket#8]
Because of #7 issue, I was looking at fork network to see if some people in other project may have worked on that issue, because I remembered many people forked and patched libRocket on their side.

I was happy to discover that a fork of maintained fork libRocket happened, named RmlUi.

Repository is there: https://github.com/mikke89/RmlUi
Website is there: https://mikke89.github.io/RmlUiDoc

There is near to 700 commits ahead of libRocket.

It would be good to:

1. submit our patches to RmlUI if they are missing.
2. rebase our fork on RmlUi so our submodule tracks upstream (we can keep our fork to keep the ability to make our own tags).

**Comment by illwieckz** [comment]
@uniquejack said on [RmlUi's gitter](https://gitter.im/RmlUi/community) about an upgrade:

> so far I haven't got any issue on upgrading to RmlUi, all I needed to do was updating the rcss decorators so far

**Comment by illwieckz** [comment]
For us the main issue with an upgrade would be probably that we forked a fork of libRocket, maybe with QFusion's own and with our own features, we would have to check for parity.

**Comment by illwieckz** [comment]
uniquejack also said:

> QFusion recently moved to RmlUi, so if there's any special feature from that fork, you probably can upgrade to RmlUi just like they did
> also, a few features you see in RmlUi were from QFusion's old fork

This is promising

**Comment by illwieckz** [comment]
For reference, this is the “_Move to RmlUi_” commit from Qfusion: https://github.com/Qfusion/qfusion/commit/985f94cfa0dc24db7b5898b82593f3fea5524225

Unfortunately this commit is very noisy because of all the `s/Rock/Rml/` renames.

**Comment by illwieckz** [comment]
@DolceTriade, do you think that's something you can do?

**Comment by DolceTriade** [comment]
Seems like a good idea. I'll see if I can find time. If QFusion moved, then we should too, because we're using their version...

**Comment by DolceTriade** [comment]
https://mikke89.github.io/RmlUiDoc/pages/rcss/animations_transitions_transforms.html

This is very cool!

**Comment by illwieckz** [comment]
Done.
